# Generated by Django 3.1.3 on 2021-01-23 20:33

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='memba'), upload_to='')),
            ],
        ),
    ]
