# Generated by Django 3.1.3 on 2021-01-23 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expose',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expose',
            name='data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expose',
            name='status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('pending', 'pending'), ('done', 'done')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='expose',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
