# Generated by Django 3.1.3 on 2021-01-27 21:05

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210123_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expose',
            name='data',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='expose',
            name='file',
            field=models.FileField(storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='memba'), upload_to='exposes/development/'),
        ),
        migrations.AlterField(
            model_name='expose',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('fail', 'fail'), ('in_progress', 'in_progress'), ('pending', 'pending')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
