# Generated by Django 3.1.3 on 2021-01-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210127_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expose',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
