# Generated by Django 3.1.3 on 2021-12-13 21:42

from core.models import ExposeUser, get_upload_path
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_s3_storage.storage
from django.core.files.base import ContentFile


def add_user_to_expose(apps, schema_editor):
    Expose = apps.get_model('core', 'Expose')
    for expose in Expose.objects.all():
        expose_user = ExposeUser.objects.get(expose_id=expose.id)
        expose.user_id = expose_user.user_id
        expose.save()


def update_expose_file(apps, schema_editor):
    Expose = apps.get_model('core', 'Expose')
    for expose in Expose.objects.exclude(file__regex=r'/user_\d+/'):
        expose.file.save(expose.file.name.split('/')[-1], ContentFile(expose.file.read()))


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_custom_20211203_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='expose',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(add_user_to_expose),
        migrations.AlterField(
            model_name='expose',
            name='file',
            field=models.FileField(
                storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='memba'),
                upload_to=get_upload_path,
            ),
        ),
        migrations.RunPython(update_expose_file),
    ]
